apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: django-monitor
  namespace: bookstore
spec:
  selector:
    matchLabels:
      app: django-api
  endpoints:
  - port: web
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: django-alerts
  namespace: bookstore
spec:
  groups:
  - name: django.rules
    rules:
    - alert: HighErrorRate
      expr: rate(django_http_responses_total_by_status_500[5m]) > 1
      for: 10m
      labels:
        severity: critical
      annotations:
        summary: High HTTP 500 error rate
        description: "Django is returning 500 errors"
    - alert: HighResponseTime
      expr: histogram_quantile(0.95, rate(django_http_requests_latency_seconds_bucket[5m])) > 2
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: High response time
        description: "95th percentile of response times is above 2 seconds"